stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
    - data/raw/master_data.csv
    - src/data/data_cleaning.py
    outs:
    - data/cleaned_ds_ready/cleaned_data.csv

  data_preparation:
    cmd: python src/data/data_preparation.py
    params:
    - Data_Preparation.test_size
    - Data_Preparation.random_state
    deps:
    - data/cleaned_ds_ready/cleaned_data.csv
    - src/data/data_preparation.py
    outs:
    - data/interim/train.csv
    - data/interim/test.csv